// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/Server3.proto

package org.github.dx88968.directrpc.coreProtos;

public final class RequestHeaderProtos {
  private RequestHeaderProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestHeaderProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string protocolName = 1;
    boolean hasProtocolName();
    String getProtocolName();
    
    // required string methodName = 2;
    boolean hasMethodName();
    String getMethodName();
  }
  public static final class RequestHeaderProto extends
      com.google.protobuf.GeneratedMessage
      implements RequestHeaderProtoOrBuilder {
    // Use RequestHeaderProto.newBuilder() to construct.
    private RequestHeaderProto(Builder builder) {
      super(builder);
    }
    private RequestHeaderProto(boolean noInit) {}
    
    private static final RequestHeaderProto defaultInstance;
    public static RequestHeaderProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestHeaderProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.internal_static_RequestHeaderProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.internal_static_RequestHeaderProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string protocolName = 1;
    public static final int PROTOCOLNAME_FIELD_NUMBER = 1;
    private java.lang.Object protocolName_;
    public boolean hasProtocolName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getProtocolName() {
      java.lang.Object ref = protocolName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          protocolName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getProtocolNameBytes() {
      java.lang.Object ref = protocolName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        protocolName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string methodName = 2;
    public static final int METHODNAME_FIELD_NUMBER = 2;
    private java.lang.Object methodName_;
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          methodName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      protocolName_ = "";
      methodName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasProtocolName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getProtocolNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getProtocolNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto)) {
        return super.equals(obj);
      }
      org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto other = (org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto) obj;
      
      boolean result = true;
      result = result && (hasProtocolName() == other.hasProtocolName());
      if (hasProtocolName()) {
        result = result && getProtocolName()
            .equals(other.getProtocolName());
      }
      result = result && (hasMethodName() == other.hasMethodName());
      if (hasMethodName()) {
        result = result && getMethodName()
            .equals(other.getMethodName());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasProtocolName()) {
        hash = (37 * hash) + PROTOCOLNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolName().hashCode();
      }
      if (hasMethodName()) {
        hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
        hash = (53 * hash) + getMethodName().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.internal_static_RequestHeaderProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.internal_static_RequestHeaderProto_fieldAccessorTable;
      }
      
      // Construct using CoreProtos.RequestHeaderProtos.RequestHeaderProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        protocolName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto.getDescriptor();
      }
      
      public org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto getDefaultInstanceForType() {
        return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto.getDefaultInstance();
      }
      
      public org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto build() {
        org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto buildPartial() {
        org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto result = new org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protocolName_ = protocolName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto) {
          return mergeFrom((org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto other) {
        if (other == org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto.getDefaultInstance()) return this;
        if (other.hasProtocolName()) {
          setProtocolName(other.getProtocolName());
        }
        if (other.hasMethodName()) {
          setMethodName(other.getMethodName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasProtocolName()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              protocolName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              methodName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string protocolName = 1;
      private java.lang.Object protocolName_ = "";
      public boolean hasProtocolName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getProtocolName() {
        java.lang.Object ref = protocolName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          protocolName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setProtocolName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        protocolName_ = value;
        onChanged();
        return this;
      }
      public Builder clearProtocolName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protocolName_ = getDefaultInstance().getProtocolName();
        onChanged();
        return this;
      }
      void setProtocolName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        protocolName_ = value;
        onChanged();
      }
      
      // required string methodName = 2;
      private java.lang.Object methodName_ = "";
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMethodName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      void setMethodName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:RequestHeaderProto)
    }
    
    static {
      defaultInstance = new RequestHeaderProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RequestHeaderProto)
  }
  
  public interface ResponseHeaderProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 resultCode = 1;
    boolean hasResultCode();
    int getResultCode();
    
    // optional string message = 2;
    boolean hasMessage();
    String getMessage();
  }
  public static final class ResponseHeaderProto extends
      com.google.protobuf.GeneratedMessage
      implements ResponseHeaderProtoOrBuilder {
    // Use ResponseHeaderProto.newBuilder() to construct.
    private ResponseHeaderProto(Builder builder) {
      super(builder);
    }
    private ResponseHeaderProto(boolean noInit) {}
    
    private static final ResponseHeaderProto defaultInstance;
    public static ResponseHeaderProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResponseHeaderProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.internal_static_ResponseHeaderProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.internal_static_ResponseHeaderProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 resultCode = 1;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private int resultCode_;
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResultCode() {
      return resultCode_;
    }
    
    // optional string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      resultCode_ = 0;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto)) {
        return super.equals(obj);
      }
      org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto other = (org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto) obj;
      
      boolean result = true;
      result = result && (hasResultCode() == other.hasResultCode());
      if (hasResultCode()) {
        result = result && (getResultCode()
            == other.getResultCode());
      }
      result = result && (hasMessage() == other.hasMessage());
      if (hasMessage()) {
        result = result && getMessage()
            .equals(other.getMessage());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResultCode()) {
        hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
        hash = (53 * hash) + getResultCode();
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.internal_static_ResponseHeaderProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.internal_static_ResponseHeaderProto_fieldAccessorTable;
      }
      
      // Construct using CoreProtos.RequestHeaderProtos.ResponseHeaderProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        resultCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto.getDescriptor();
      }
      
      public org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto getDefaultInstanceForType() {
        return org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto.getDefaultInstance();
      }
      
      public org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto build() {
        org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto buildPartial() {
        org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto result = new org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto) {
          return mergeFrom((org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto other) {
        if (other == org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resultCode_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 resultCode = 1;
      private int resultCode_ ;
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResultCode() {
        return resultCode_;
      }
      public Builder setResultCode(int value) {
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = 0;
        onChanged();
        return this;
      }
      
      // optional string message = 2;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:ResponseHeaderProto)
    }
    
    static {
      defaultInstance = new ResponseHeaderProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ResponseHeaderProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestHeaderProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RequestHeaderProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseHeaderProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResponseHeaderProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030src/protos/Server3.proto\">\n\022RequestHea" +
      "derProto\022\024\n\014protocolName\030\001 \002(\t\022\022\n\nmethod" +
      "Name\030\002 \002(\t\":\n\023ResponseHeaderProto\022\022\n\nres" +
      "ultCode\030\001 \002(\r\022\017\n\007message\030\002 \001(\tB\'\n\nCorePr" +
      "otosB\023RequestHeaderProtos\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RequestHeaderProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RequestHeaderProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RequestHeaderProto_descriptor,
              new java.lang.String[] { "ProtocolName", "MethodName", },
              org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto.class,
              org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.RequestHeaderProto.Builder.class);
          internal_static_ResponseHeaderProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ResponseHeaderProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ResponseHeaderProto_descriptor,
              new java.lang.String[] { "ResultCode", "Message", },
              org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto.class,
              org.github.dx88968.directrpc.coreProtos.RequestHeaderProtos.ResponseHeaderProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
