// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/Server4.proto

package org.github.dx88968.directrpc.coreProtos;

public final class RpcHeaderProtos {
  private RpcHeaderProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RpcRequestHeaderProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 callid = 1;
    boolean hasCallid();
    int getCallid();
  }
  public static final class RpcRequestHeaderProto extends
      com.google.protobuf.GeneratedMessage
      implements RpcRequestHeaderProtoOrBuilder {
    // Use RpcRequestHeaderProto.newBuilder() to construct.
    private RpcRequestHeaderProto(Builder builder) {
      super(builder);
    }
    private RpcRequestHeaderProto(boolean noInit) {}
    
    private static final RpcRequestHeaderProto defaultInstance;
    public static RpcRequestHeaderProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public RpcRequestHeaderProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.internal_static_RpcRequestHeaderProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.internal_static_RpcRequestHeaderProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 callid = 1;
    public static final int CALLID_FIELD_NUMBER = 1;
    private int callid_;
    public boolean hasCallid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCallid() {
      return callid_;
    }
    
    private void initFields() {
      callid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCallid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, callid_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, callid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto)) {
        return super.equals(obj);
      }
      org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto other = (org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto) obj;
      
      boolean result = true;
      result = result && (hasCallid() == other.hasCallid());
      if (hasCallid()) {
        result = result && (getCallid()
            == other.getCallid());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCallid()) {
        hash = (37 * hash) + CALLID_FIELD_NUMBER;
        hash = (53 * hash) + getCallid();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.internal_static_RpcRequestHeaderProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.internal_static_RpcRequestHeaderProto_fieldAccessorTable;
      }
      
      // Construct using CoreProtos.RpcHeaderProtos.RpcRequestHeaderProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        callid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto.getDescriptor();
      }
      
      public org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto getDefaultInstanceForType() {
        return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto.getDefaultInstance();
      }
      
      public org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto build() {
        org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto buildPartial() {
        org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto result = new org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.callid_ = callid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto) {
          return mergeFrom((org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto other) {
        if (other == org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto.getDefaultInstance()) return this;
        if (other.hasCallid()) {
          setCallid(other.getCallid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCallid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              callid_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 callid = 1;
      private int callid_ ;
      public boolean hasCallid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCallid() {
        return callid_;
      }
      public Builder setCallid(int value) {
        bitField0_ |= 0x00000001;
        callid_ = value;
        onChanged();
        return this;
      }
      public Builder clearCallid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        callid_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:RpcRequestHeaderProto)
    }
    
    static {
      defaultInstance = new RpcRequestHeaderProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RpcRequestHeaderProto)
  }
  
  public interface RpcResponseHeaderProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 callid = 1;
    boolean hasCallid();
    int getCallid();
  }
  public static final class RpcResponseHeaderProto extends
      com.google.protobuf.GeneratedMessage
      implements RpcResponseHeaderProtoOrBuilder {
    // Use RpcResponseHeaderProto.newBuilder() to construct.
    private RpcResponseHeaderProto(Builder builder) {
      super(builder);
    }
    private RpcResponseHeaderProto(boolean noInit) {}
    
    private static final RpcResponseHeaderProto defaultInstance;
    public static RpcResponseHeaderProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public RpcResponseHeaderProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.internal_static_RpcResponseHeaderProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.internal_static_RpcResponseHeaderProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 callid = 1;
    public static final int CALLID_FIELD_NUMBER = 1;
    private int callid_;
    public boolean hasCallid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCallid() {
      return callid_;
    }
    
    private void initFields() {
      callid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCallid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, callid_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, callid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto)) {
        return super.equals(obj);
      }
      org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto other = (org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto) obj;
      
      boolean result = true;
      result = result && (hasCallid() == other.hasCallid());
      if (hasCallid()) {
        result = result && (getCallid()
            == other.getCallid());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCallid()) {
        hash = (37 * hash) + CALLID_FIELD_NUMBER;
        hash = (53 * hash) + getCallid();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.internal_static_RpcResponseHeaderProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.internal_static_RpcResponseHeaderProto_fieldAccessorTable;
      }
      
      // Construct using CoreProtos.RpcHeaderProtos.RpcResponseHeaderProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        callid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto.getDescriptor();
      }
      
      public org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto getDefaultInstanceForType() {
        return org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto.getDefaultInstance();
      }
      
      public org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto build() {
        org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto buildPartial() {
        org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto result = new org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.callid_ = callid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto) {
          return mergeFrom((org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto other) {
        if (other == org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto.getDefaultInstance()) return this;
        if (other.hasCallid()) {
          setCallid(other.getCallid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCallid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              callid_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 callid = 1;
      private int callid_ ;
      public boolean hasCallid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCallid() {
        return callid_;
      }
      public Builder setCallid(int value) {
        bitField0_ |= 0x00000001;
        callid_ = value;
        onChanged();
        return this;
      }
      public Builder clearCallid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        callid_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:RpcResponseHeaderProto)
    }
    
    static {
      defaultInstance = new RpcResponseHeaderProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RpcResponseHeaderProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcRequestHeaderProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RpcRequestHeaderProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcResponseHeaderProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RpcResponseHeaderProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030src/protos/Server4.proto\"\'\n\025RpcRequest" +
      "HeaderProto\022\016\n\006callid\030\001 \002(\r\"(\n\026RpcRespon" +
      "seHeaderProto\022\016\n\006callid\030\001 \002(\rB#\n\nCorePro" +
      "tosB\017RpcHeaderProtos\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RpcRequestHeaderProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RpcRequestHeaderProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RpcRequestHeaderProto_descriptor,
              new java.lang.String[] { "Callid", },
              org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto.class,
              org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcRequestHeaderProto.Builder.class);
          internal_static_RpcResponseHeaderProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RpcResponseHeaderProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RpcResponseHeaderProto_descriptor,
              new java.lang.String[] { "Callid", },
              org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto.class,
              org.github.dx88968.directrpc.coreProtos.RpcHeaderProtos.RpcResponseHeaderProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
